### Titanic dataset

Today, we will be working on titianic dataset using the github url.

In [71]:
import pandas as pd 
pd.set_option('display.max_columns', None) # Show all columns
pd.set_option('display.width', 1000) # doesnt wrap the columns

<h5> Importing dataset via URL <h5>

In [72]:

url="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv?utm_source=chatgpt.com" 
pd.read_csv(url, header=None)

              0         1       2                                                  3       4    5      6      7                 8        9      10        11
0    PassengerId  Survived  Pclass                                               Name     Sex  Age  SibSp  Parch            Ticket     Fare  Cabin  Embarked
1              1         0       3                            Braund, Mr. Owen Harris    male   22      1      0         A/5 21171     7.25    NaN         S
2              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   38      1      0          PC 17599  71.2833    C85         C
3              3         1       3                             Heikkinen, Miss. Laina  female   26      0      0  STON/O2. 3101282    7.925    NaN         S
4              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   35      1      0            113803     53.1   C123         S
..           ...       ...     ...                                                ...     ...  ...    ...    ...               ...      ...    ...       ...
887          887         0       2                              Montvila, Rev. Juozas    male   27      0      0            211536       13    NaN         S
888          888         1       1                       Graham, Miss. Margaret Edith  female   19      0      0            112053       30    B42         S
889          889         0       3           Johnston, Miss. Catherine Helen "Carrie"  female  NaN      1      2        W./C. 6607    23.45    NaN         S
890          890         1       1                              Behr, Mr. Karl Howell    male   26      0      0            111369       30   C148         C
891          891         0       3                                Dooley, Mr. Patrick    male   32      0      0            370376     7.75    NaN         Q

[892 rows x 12 columns]

In [73]:
# Changing header names  
# header must be overwrite again. 
df=pd.read_csv( 
    url, 
    header=0, 
    names=['id', 'survived', 'passengerClass', 'Name', 'Gender', 'Age', 'SiblingsSpouseNumber', 'ParentsChildNumbers','TicketNumber', 'Fare', 'Cabin', 'Embarked']
    )  
print(df.head(5))

   id  survived  passengerClass                                               Name  Gender   Age  SiblingsSpouseNumber  ParentsChildNumbers      TicketNumber     Fare Cabin Embarked
0   1         0               3                            Braund, Mr. Owen Harris    male  22.0                     1                    0         A/5 21171   7.2500   NaN        S
1   2         1               1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0                     1                    0          PC 17599  71.2833   C85        C
2   3         1               3                             Heikkinen, Miss. Laina  female  26.0                     0                    0  STON/O2. 3101282   7.9250   NaN        S
3   4         1               1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0                     1                    0            113803  53.1000  C123        S
4   5         0               3                           Allen, Mr. William Henry    male  35.0                     0                    0            373450   8.0500   NaN        S

In [74]:
# use of index_col and usecols 
# index_cols is to tell panda not to use the first cols as the header, set it False in parameters.  
df1=pd.read_csv(url, index_col='PassengerId', dtype={'Survived':'float'}, usecols=['PassengerId','Survived','Pclass'])  # choosing selective cols 
print(df1.head(5)) #DTYPE CAN CHANGE THE TYPE OF THE VARIABLE

             Survived  Pclass
PassengerId
1                 0.0       3
2                 1.0       1
3                 1.0       3
4                 1.0       1
5                 0.0       3

In [75]:
# skipping rows 
df2=pd.read_csv(url) 
print(df2.head(5))

   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4            5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S

In [76]:
df3=pd.read_csv(url, skiprows=[0,1,2,3,4], skip_blank_lines=True) 
print(df3) # looked it skipped the rows that I asked it to.

       5  0  3                           Allen, Mr. William Henry    male    35  0.1  0.2      373450     8.05 Unnamed: 10  S
0      6  0  3                                   Moran, Mr. James    male   NaN    0    0      330877   8.4583         NaN  Q
1      7  0  1                            McCarthy, Mr. Timothy J    male  54.0    0    0       17463  51.8625         E46  S
2      8  0  3                     Palsson, Master. Gosta Leonard    male   2.0    3    1      349909  21.0750         NaN  S
3      9  1  3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0    0    2      347742  11.1333         NaN  S
4     10  1  2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0    1    0      237736  30.0708         NaN  C
..   ... .. ..                                                ...     ...   ...  ...  ...         ...      ...         ... ..
881  887  0  2                              Montvila, Rev. Juozas    male  27.0    0    0      211536  13.0000         NaN  S
882  888  1  1                       Graham, Miss. Margaret Edith  female  19.0    0    0      112053  30.0000         B42  S
883  889  0  3           Johnston, Miss. Catherine Helen "Carrie"  female   NaN    1    2  W./C. 6607  23.4500         NaN  S
884  890  1  1                              Behr, Mr. Karl Howell    male  26.0    0    0      111369  30.0000        C148  C
885  891  0  3                                Dooley, Mr. Patrick    male  32.0    0    0      370376   7.7500         NaN  Q

[886 rows x 12 columns]

In [77]:
df3.describe()

                5           0           3          35         0.1         0.2        8.05
count  886.000000  886.000000  886.000000  709.000000  886.000000  886.000000  886.000000
mean   448.500000    0.382619    2.309255   29.688533    0.522573    0.383747   32.219347
std    255.910466    0.486301    0.835149   14.568099    1.105226    0.807819   49.790966
min      6.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%    227.250000    0.000000    2.000000   20.000000    0.000000    0.000000    7.903100
50%    448.500000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%    669.750000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max    891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [78]:
df3.shape # rows and columns

(886, 12)

That's it for day 1, will start from day 2 tomorrow.